ARG NODE_VERSION=24-bookworm-slim

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm ci

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 5173

# In development, we run the vite server for hot reload. So we need to bind to 0.0.0.0 to allow access from outside the container.
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]