networks:
  web:
    external: true

services:
  benjrm:
    image: ghcr.io/benjrm/benjrm:dev
    depends_on:
      db:
        condition: service_healthy
      idp:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./config:/config
    networks:
      - default
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.benjrm.priority: 10
      traefik.http.routers.benjrm.rule: Host("${DOMAIN}") || Host("www.${DOMAIN}")
  
  db:
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: benjrm
      POSTGRES_USER: benjrm
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benjrm -d benjrm"]
      start_period: 30s
      start_interval: 2s
      interval: 30s
      timeout: 2s
      retries: 10
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql

  db-idp:
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: benjrm
      POSTGRES_USER: benjrm
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benjrm -d benjrm"]
      start_period: 30s
      start_interval: 2s
      interval: 30s
      timeout: 2s
      retries: 10
    env_file:
      - .env
    volumes:
      - db-idp:/var/lib/postgresql

  idp:
    image: voidauth/voidauth:1.15.1
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ${DOMAIN}
      web:
    environment:
      APP_URL: ${OIDC_PUBLIC_IDP_URL}
      DB_HOST: db-idp
      DB_ADAPTER: postgres
      DB_NAME: benjrm
      DB_USER: benjrm
      DB_PASSWORD: ${DATABASE_PASSWORD}
      STORAGE_KEY: ${IDP_STORAGE_KEY}
      SIGNUP: ${IDP_SIGNUP}
      SIGNUP_REQUIRES_APPROVAL: ${IDP_APPROVAL_REQUIRED}
      OIDC_BENJRM_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_BENJRM_CLIENT_DISPLAY_NAME: ${OIDC_CLIENT_NAME}
      OIDC_BENJRM_CLIENT_HOMEPAGE_URL: ${PUBLIC_URL}
      OIDC_BENJRM_CLIENT_REDIRECT_URLS: ${PUBLIC_URL}/auth/oidc/callback
      OIDC_BENJRM_CLIENT_POST_LOGOUT_URLS: ${PUBLIC_URL}/*
      OIDC_BENJRM_CLIENT_SKIP_CONSENT: ${IDP_CLIENT_SKIP_CONSENT}
      OIDC_BENJRM_CLIENT_GRANT_TYPES: authorization_code
      APP_PORT: 3000

    healthcheck:
      start_period: 5s
      start_interval: 2s
      interval: 2s
      timeout: 2s
      retries: 10

    labels:
      traefik.enable: true
      traefik.http.routers.benjrm_idp.priority: 100
      traefik.http.routers.benjrm_idp.rule: Host("${DOMAIN}") && PathPrefix(`/idp`)
      traefik.http.services.benjrm_idp.loadbalancer.server.port: 3000

volumes:
  db:
  db-idp:
